services:
  link-shortener:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5431:5432
volumes:
  postgres_data:
    driver: local